#!/usr/bin/env zsh
if  [[ -x `which brew` ]]; then
    alias b='brew'
    alias be='brew edit'
    alias bs='brew search'
    alias bi='brew install --use-llvm'
    alias bin='brew info'
    alias bui='brew uninstall'
fi
# vim: set syn=zsh:
