#!/usr/bin/env zsh

# Set pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

# Set pip need virtualenv
export PIP_REQUIRE_VIRTUALENV=true

# Set pip auto start virtualenv
export PIP_RESPECT_VIRTUALENV=true
