#!/usr/bin/env zsh
# Set Python path on brew
if [[ -x $(brew --prefix)/share/python ]]; then
  path=($(brew --prefix)/share/python $path)
fi

# Set brew-pip path
export PYTHONPATH=$(brew --prefix)/lib/python2.7/site-packages

typeset -U PYTHONPATH

# vim: set syn=zsh:
