#!/usr/bin/env zsh

# Set pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

# Setup python site-packages
PYTHON_PACKAGES=/usr/local/share/python
if [[ -d $PYTHON_PACKAGES && -n `brew list | grep python` ]]; then
    path=($PYTHON_PACKAGES $path)
fi
